# Generated by Django 5.0.1 on 2024-01-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_category_girl_girls_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='girls',
            options={'ordering': ('-created_at',), 'verbose_name': 'Girl', 'verbose_name_plural': 'Girls'},
        ),
    ]
