# Generated by Django 5.0.1 on 2024-01-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.TimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
